import {analytic} from "./analytic";

export const AnalyticsEvents = {
  BOUNTY_CREATED: [analytic("ga4")],
  BOUNTY_ACTIVE: [analytic("ga4")],
  BOUNTY_CANCELED: [analytic("ga4")],
  BOUNTY_CLOSED: [analytic("ga4")],
  LOCK_UNLOCK_NETWORK: [analytic("ga4")],
  DELEGATE_UNDELEGATE: [analytic("ga4")],
  LOCK_UNLOCK_REGISTRY: [analytic("ga4")],
  PULL_REQUEST_OPEN: [analytic("ga4")],
  PULL_REQUEST_READY: [analytic("ga4")],
  PULL_REQUEST_CANCELED: [analytic("ga4")],
  PULL_REQUEST_MERGED: [analytic("ga4")],
  MERGE_PROPOSAL_OPEN: [analytic("ga4")],
  MERGE_PROPOSAL_DISPUTED: [analytic("ga4")],
  MERGE_PROPOSAL_READY: [analytic("ga4")],
  MERGE_PROPOSAL_ACCEPTED: [analytic("ga4")],
  MERGE_PROPOSAL_CANCELLED: [analytic("ga4")],
  FUNDING_REQUEST_CREATED: [analytic("ga4")],
  BOUNTY_FUNDED: [analytic("ga4")],
  BOUNTY_NETWORK_CREATED: [analytic("ga4")],
  BOUNTY_NETWORK_UPDATED: [analytic("ga4")],
  NFT_MINTED: [analytic("ga4")],
  BOUNTY_PAYMENT: [analytic("ga4")],
  BOUNTY_NEW_COMMENT: [analytic("ga4")],
  REGISTRY_UPDATED: [analytic("ga4")],
}