export const EventNameActionsMap = {
  getBountyAmountUpdatedEvents: 'BountyAmountUpdated',
  getBountyCanceledEvents: 'BountyCanceled',
  getBountyClosedEvents: 'BountyClosed',
  getBountyCreatedEvents: 'BountyCreated',
  getBountyFundedEvents: 'BountyFunded',
  getChangeAllowedTokensEvents: 'ChangeAllowedTokens',
  getNetworkRegisteredEvents: 'NetworkRegistered',
  getUserLockedAmountChangedEvents: 'UserLockedAmountChanged',
  getOraclesChangedEvents: 'OraclesChanged',
  getOraclesTransferEvents: 'OraclesTransfer',
  getBountyProposalCreatedEvents: 'BountyProposalCreated',
  getBountyProposalDisputedEvents: 'BountyProposalDisputed',
  getBountyProposalRefusedEvents: 'BountyProposalRefused',
  getBountyPullRequestCanceledEvents: 'BountyPullRequestCanceled',
  getBountyPullRequestCreatedEvents: 'BountyPullRequestCreated',
  getBountyPullRequestReadyForReviewEvents: 'BountyPullRequestReadyForReview',
  getTransferEvents: 'Transfer', 
}